---
- name: Install yum-utils
  ansible.builtin.package:
    name: yum-utils
    state: present

- name: Add RHEL repository
  shell: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
